import os
import time
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
DOC_FILE = os.path.join(PROJECT_DIR, "script_documentation.txt")
EXCLUDE_DIRS = {"medidoc", "venv", ".git", "__pycache__", "data", "data_staging"}

def parse_purpose(filepath):
    purpose = "Purpose: Not specified."
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for i in range(10): # Check first 10 lines
                line = f.readline()
                if not line:
                    break
                if line.strip().startswith("# Purpose:"):
                    purpose = line.strip().replace("# Purpose:", "Purpose:").strip()
                    # Some files might have multiline comments, but we take just the first one for simplicity
                    break
    except Exception:
        pass
    return purpose

def generate_docs():
    print("Regenerating script_documentation.txt...")
    scripts_info = []
    
    for root, dirs, files in os.walk(PROJECT_DIR):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for file in files:
            if file.endswith(".py"):
                filepath = os.path.join(root, file)
                rel_path = os.path.relpath(filepath, PROJECT_DIR)
                purpose = parse_purpose(filepath)
                scripts_info.append((rel_path, purpose))
                
    scripts_info.sort()
    
    with open(DOC_FILE, 'w', encoding='utf-8') as f:
        f.write("Medidoc Script Documentation\n")
        f.write("============================\n")
        f.write("This document outlines all the Python script files present in the MedidocAI workspace and describes their primary purpose.\n")
        f.write("*(Note: This file is automatically generated and updated via auto_doc.py)*\n\n")
        
        for idx, (rel_path, purpose) in enumerate(scripts_info, 1):
            f.write(f"{idx}. {rel_path}\n")
            f.write(f"   {purpose}\n\n")
    print(f"Documentation updated! Total scripts documented: {len(scripts_info)}")

class DocChangeHandler(FileSystemEventHandler):
    def on_modified(self, event):
        if event.is_directory:
            return
        if event.src_path.endswith(".py") and not event.src_path.endswith("auto_doc.py"):
            generate_docs()
            
    def on_created(self, event):
        if event.is_directory:
            return
        if event.src_path.endswith(".py"):
            generate_docs()

def start_watcher():
    generate_docs() # Initial generation
    
    event_handler = DocChangeHandler()
    observer = Observer()
    observer.schedule(event_handler, PROJECT_DIR, recursive=True)
    observer.start()
    print(f"Started watching {PROJECT_DIR} for new or modified Python scripts...")
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()

if __name__ == "__main__":
    start_watcher()
